### ISSUE TITLE
Not SSR friendly

### ISSUE THREAD

**Issue by theoinglis** [scaleflex/react-cloudimage-responsive#6]
I have had to workaround this for now, but I would recommend looking at the user agent and allowing that to make a good prediction of max widths that can be updated when the image is rendered in the frontend

**Comment by dzmitry-stramavus** [comment]
hey @theoinglis ,

would you like to describe" looking at the user agent and allowing that to make a good prediction of max widths " how do you see this?

**Comment by theoinglis** [comment]
Hi @dzmitry-stramavus, thanks for following up.

I use a package called [mobile-detect](https://github.com/hgoebl/mobile-detect.js) to predict the device size and then use that to define max widths the image is likely to be. However, adding this would mean that you would need a user to pass in the user agent which I don't think you would want to do. As an optional parameter it might be useful though?

Anyway, I think the key task to achieve is simply making it SSR friendly by removing references to window, etc.

**Comment by dwafotapa** [comment]
Backing up @theoinglis 's request here.

Using Next.js and server-side rendering, I've had to add this module https://github.com/martpie/next-transpile-modules as your library is not transpiled to es5.
Also, I've had to create wrappers around CloudimageProvider, Img, BackgroundImg to render them on clients only.

Could you work on a more SSR-friendly version please?

**Comment by dzmitry-stramavus** [comment]
yep, I will work on it in the next release

**Comment by theoinglis** [comment]
Hi @dzmitry-stramavus. Has there been any progress on this?

**Comment by dzmitry-stramavus** [comment]
@theoinglis , hey, our team was on vacation. We will try to find time during the week on it.

**Comment by rwproj** [comment]
hey, how is it going with making library SSR friendly? wanted to use it in our project but the SSR incompatibility makes us sad :(

**Comment by dzmitry-stramavus** [comment]
done in **1.6.5 version**

**Comment by ddominiqq** [comment]
Still failing for me on the server-side:
`TypeError: Cannot read property 'config' of undefined`

Seems like the context.config in /dist/index.js is not passed properly.
